#!/bin/bash
#
# /etc/rc.d/init.d/dnlmanager
#
# dnl manager daemon
#
# chkconfig: 2345 80 20
# description: dnl manager daemon used to start the server and keep it updated
# processname: ShooterGameServer
# config: /etc/dnlmanager/dnlmanager.cfg

### BEGIN INIT INFO
# Provides:          dnl manager deamon
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: dnl manager deamon
# Description:       dnl manager daemon used to start the server and keep it updated
#
### END INIT INFO

# Using the lsb functions to perform the operations.
. /etc/rc.d/init.d/functions

# Global variables
source /etc/dnlmanager/dnlmanager.cfg

NAME="ShooterGameServer"
LOGFILE="${logdir}/${NAME}.log"
DAEMON="/usr/bin/dnlmanager"

GREEN="\\033[1;32m"
RED="\\033[1;31m"
NORMAL="\\033[0;39m"

SVCNAME="${0##*/}"
INSTANCE="${SVCNAME#*.}"

if [ "$INSTANCE" == "$SVCNAME" ]; then
  INSTANCE="$2"
fi

set -e

# If the daemon is not there, then exit.
test -x $DAEMON || exit 5

function start_instance(){
  local INSTANCE="$1"
  PID="$(<"/var/run/dnlmanager.${INSTANCE}.pid")"
  if [ -n "$PID" ] && kill -0 "$PID" >/dev/null 2>&1; then
    if grep " ${PID} .* ${DAEMON}" <(ps -ef) >/dev/null 2>&1; then
      echo "$NAME @${INSTANCE} is already running"
      return 0
    fi
  fi
  echo -n "Starting $NAME @${INSTANCE}: "
  ulimit -n 100000
  "${DAEMON}" run "@${INSTANCE}" &
  PID="$!"

  sleep 5
  if kill -0 "$PID" >/dev/null 2>&1; then
    echo "$PID" >"/var/run/dnlmanager.${INSTANCE}.pid"
    touch "/var/lock/subsys/dnlmanager.${INSTANCE}"
    echo "[" "$GREEN" " OK " "$NORMAL" "]"
    return 0
  else
    echo "[" "$RED" " FAILED " "$NORMAL" "]"
    return 1
  fi
}

function start_all_instances(){
  local nosuccess=0
  local anyfailure=0
  for instance in $("${DAEMON}" list-instances --brief); do
    if start_instance "$instance"; then
      nosuccess=0
    else
      anyfailure=1
    fi
  done

  return $nosuccess
}

function stop_instance(){
  local INSTANCE="$1"
  echo -n "Stopping $NAME @${INSTANCE}: "
  "${DAEMON}" stop "@${INSTANCE}" &
  rm -f "/var/lock/subsys/dnlmanager.${INSTANCE}"
  rm -f "/var/run/dnlmanager.${INSTANCE}.pid"
  echo "[" "$GREEN" " OK " "$NORMAL" "]"
  return 0
}

case "$1" in
  start)
    if [ -n "$INSTANCE" ]; then
      start_instance "$INSTANCE"
      exit $?
    else
      if start_all_instances; then
        touch /var/lock/subsys/dnlmanager
        exit 0
      else
        exit 1
      fi
    fi
  ;;

  stop)
    if [ -n "$INSTANCE" ]; then
      stop_instance "$INSTANCE"
      exit $?
    else
      for instance in $("${DAEMON}" list-instances --brief); do
        stop_instance "$instance"
      done
      rm -f "/var/lock/subsys/dnlmanager"
      exit $?
    fi
  ;;

  restart)
    "$0" stop
    "$0" start
  ;;

  status)
    "$DAEMON" status "@${INSTANCE:-all}"
    exit 0
  ;;

  *)
    # For invalid arguments, print the usage message.
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
  ;;
esac
